import type { ProviderType } from '../types/defaultProviderTypes';
    
export const providerTypes: ProviderType[] = [
  {
    id: "1",
    name: "Allopathic & Osteopathic Physicians",
    requirements: {
      stateLicense: true,
      deaCds: true,
      boardCertification: true,
      degree: true,
      residency: true,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "2",
    name: "Behavioral Health & Social Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: false,
      boardCertification: true,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "3",
    name: "Chiropractic Providers",
    requirements: {
      stateLicense: true,
      deaCds: false,
      boardCertification: false,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "4",
    name: "Dental Providers",
    requirements: {
      stateLicense: true,
      deaCds: true,
      boardCertification: false,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "5",
    name: "Dietary & Nutritional Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: false,
      boardCertification: false,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "6",
    name: "Emergency Medical Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: false,
      boardCertification: false,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "7",
    name: "Eye and Vision Services Providers",
    requirements: {
      stateLicense: true,
      deaCds: true,
      boardCertification: true,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "8",
    name: "Nursing Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: false,
      boardCertification: false,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "9",
    name: "Pharmacy Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: true,
      boardCertification: true,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "10",
    name: "Physician Assistants & Advanced Practice Nursing Providers",
    requirements: {
      stateLicense: true,
      deaCds: true,
      boardCertification: true,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "11",
    name: "Podiatric Medicine & Surgery Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: true,
      boardCertification: true,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
  {
    id: "12",
    name: "Speech, Language and Hearing Service Providers",
    requirements: {
      stateLicense: true,
      deaCds: false,
      boardCertification: false,
      degree: true,
      residency: false,
      malpracticeInsurance: true,
      backgroundCheck: true,
      workHistory: true,
    },
  },
]; 